### ISSUE TITLE
No longer being indexed?

### ISSUE THREAD

**Issue by seltmann** [Extended-Bee-Network/bee-interaction-database#15]
@jhpoelen This repo is no longer indexed by GloBI and I cannot find the error. Help?

**Comment by jhpoelen** [comment]
@seltmann having a look. 

Some notes:

1. According to a recent review at https://travis-ci.org/github/Extended-Bee-Network/bee-interaction-database/builds/738436408 , there's 3068 interaction in the datasets.
2. your data was last updated on GloBI's index server at 2020-12-08T23:54:05.408Z
3. elton was able to extract interaction from the server's most recent versioned copy
```
$ elton interactions Extended-Bee-Network/bee-interaction-database | head -n1
argumentTypeId	sourceOccurrenceId	sourceCatalogNumber	sourceCollectionCode	sourceCollectionId	sourceInstitutionCode	sourceTaxonId	sourceTaxonName	sourceTaxonRank	sourceTaxonPathIds	sourceTaxonPath	sourceTaxonPathNames	sourceBodyPartId	sourceBodyPartName	sourceLifeStageId	sourceLifeStageName	sourceSexId	sourceSexName	interactionTypeId	interactionTypeName	targetOccurrenceId	targetCatalogNumber	targetCollectionCode	targetCollectionId	targetInstitutionCode	targetTaxonId	targetTaxonName	targetTaxonRank	targetTaxonPathIds	targetTaxonPath	targetTaxonPathNames	targetBodyPartId	targetBodyPartName	targetLifeStageId	targetLifeStageName	targetSexId	targetSexName	basisOfRecordId	basisOfRecordName	http://rs.tdwg.org/dwc/terms/eventDate	decimalLatitude	decimalLongitude	localityId	localityName	referenceDoi	referenceUrl	referenceCitation	namespace	citation	archiveURI	lastSeenAt	contentHash	eltonVersion
listing interactions [Extended-Bee-Network/bee-interaction-database]... https://en.wiktionary.org/wiki/support				https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=699376	Melissodes pullatella				Female	http://purl.obolibrary.org/obo/RO_0002622	visitsFlowersOf						https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=535920	Grindelia integrifolia x Grindelia nana				44.60417	-123.2389			10.1007/s10531-010-9897-7	https://doi.org/10.1007/s10531-010-9897-7	Severns, P. M. & Moldenke, A. R. (2010) Management tradeoffs between focal species and biodiversity: Endemic plant) conservation and solitary bee extinction. Biodivers. Conserv. 19, 3605-3609.	Extended-Bee-Network/bee-interaction-database	Seltmann, K., Van Wagner, J., Behm, R., Brown, Z., Tan, E., & Liu, K. (2020). BID: A project to share biotic interaction and ecological trait data about bees (Hymenoptera: Anthophila). UC Santa Barbara: Cheadle Center for Biodiversity and Ecological Restoration. Retrieved from https://escholarship.org/uc/item/1g21k7bf	https://github.com/Extended-Bee-Network/bee-interaction-database/archive/3360aeafab9b30b34ddb45ddfd170eda69536904.zip	2020-12-08T23:54:05.611Z	0b9e47a7178db8a49416e4f4a6e5e1c21b27aae1687756886af9b46a57ecc0f0	0.10.4
```
4. no errors are apparent in the most recent indexing logs
5. however, on https://globalbioticinteractions.org/datasets page, the dataset Extended-Bee-Network/bee-interaction-database does not appear. 

continuing to investigate, more later.

**Comment by jhpoelen** [comment]
After updating the GloBI index to a more recent version, the Extended-Bee-Network/bee-interaction-database reappeared, see attached screenshot.

![Screenshot from 2020-12-10 07-54-31](https://user-images.githubusercontent.com/1084872/101795787-19bd5300-3abd-11eb-9fab-b064ac5c47e9.png)
![Screenshot from 2020-12-10 07-54-20](https://user-images.githubusercontent.com/1084872/101795792-1aee8000-3abd-11eb-96a5-e8a2deacd0b0.png)
 
The older index (generated 1 Dec 2020, over a week ago), did not have the interaction database. Still looking into root cause.

**Comment by jhpoelen** [comment]
@seltmann I noticed that you've been actively working on the dataset in the recent past. However, travis-ci.org is not showing automated reviews after each commit. If you enable automated reviews, you can see whether there's unexpected notes, like "no interactions found". Having automated travis reviews would have helped to pin point the root cause of the non-indexing by inspecting the build log (aka review log). Can you please enable this?

**Comment by jhpoelen** [comment]
@seltmann I've identified the most likely cause of the Extended-Bee-Network/bee-interaction-database not being indexed, and you fixed this some days ago via:

https://github.com/Extended-Bee-Network/bee-interaction-database/commit/9779f5682efe9268b3725b2c38b680d44c819e4f

Currently, a malformed globi.json will prevent GloBI from understanding and indexing your datasets.

In summary - you found an unexpected result because the GloBI index wasn't updated (due to maintenance work) for about a week, and that older index did not include an older version of the bee-interaction-database because of syntax issues on globi.json .

**Comment by seltmann** [comment]
@jhpoelen perfect, thanks!
